apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - name: dotnet
          image: microsoft/dotnet-samples:aspnetapp
          ports:
            - containerPort: 80